/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OclVanitygen */

#ifndef _Included_OclVanitygen
#define _Included_OclVanitygen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OclVanitygen
 * Method:    oclGenerateAddress
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_OclVanitygen_oclGenerateAddress
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     OclVanitygen
 * Method:    oclGetPrivateKey
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_OclVanitygen_oclGetPrivateKey
  (JNIEnv *, jclass);

/*
 * Class:     OclVanitygen
 * Method:    oclGetProgress
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_OclVanitygen_oclGetProgress
  (JNIEnv *, jclass);

/*
 * Class:     OclVanitygen
 * Method:    oclGetEquipment
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_OclVanitygen_oclGetEquipment
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
