/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Vanitygen */

#ifndef _Included_Vanitygen
#define _Included_Vanitygen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Vanitygen
 * Method:    generateAddress
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Vanitygen_generateAddress
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Vanitygen
 * Method:    getPrivaeKey
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Vanitygen_getPrivaeKey
  (JNIEnv *, jobject);

/*
 * Class:     Vanitygen
 * Method:    getProgress
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Vanitygen_getProgress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
