/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VanitygenJni */

#ifndef _Included_VanitygenJni
#define _Included_VanitygenJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VanitygenJni
 * Method:    generateAddress
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_VanitygenJni_generateAddress
  (JNIEnv *, jclass, jstring);

/*
 * Class:     VanitygenJni
 * Method:    getPrivateKey
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_VanitygenJni_getPrivateKey
  (JNIEnv *, jclass);

/*
 * Class:     VanitygenJni
 * Method:    getProgress
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_VanitygenJni_getProgress
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
